language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - '4.1'
  - 'iojs'
addons:
  apt:
    sources:
    - ruby
before_script:
  - gem install sass
  - bower install
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt build-deploy --custom=gapminder || grunt --custom=gapminder'
  - grunt test
