language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - '4.1'
  - 'iojs'
addons:
  apt:
    sources:
    - ruby
    - s3cmd
before_script:
  - gem install sass
  - bower install
script:
  - gulp build
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh deploy.sh'
