language: node_js
node_js:
  - '0.10'
before_install:
  - sudo apt-get update
before_script:
  - sudo apt-get install ruby
  - gem install sass
  - bower install
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt build-deploy --custom=gapminder || grunt --custom=gapminder'
