language: node_js
sudo: false
node_js:
  - '4.1'
addons:
  apt:
    packages:
    - s3cmd
    - ruby
install:
  - gem install sass
  - gem install scss_lint
  - npm install -g gulp
before_script:
  - npm install
script:
  - gulp build
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh deploy.sh || true'

after_success:
  .cicd/beta_npm_ver.js
  - gulp build

deploy:
  skip_cleanup: true
  provider: npm
  email: "konzeptmeister@gmail.com"
  api_key:
    secure: "XVJ/QwnTYMNEUMtAcvmVdh6EHndHcEqzdJUe7JYYRXmA2qxhRGIC8VlnK9GKZOS3ACSDygp1lCam+BA5ZYy4QhvsMsPQukWeon6K8Zcerg8Lg3XfxXBilKATf83DQ0PZslus1XgynZmNgUCkJ61rhAhLVOx0iIpetMOHTZ3oJak="
  on:
    branch: develop
    node: 4.1
    condition: "-e /tmp/deployment.flag"
