language: node_js
sudo: false
node_js:
  - '4.1'
addons:
  apt:
    packages:
    - s3cmd
    - ruby
install:
  - gem install sass
  - gem install scss_lint
  - npm install -g gulp
before_script:
  - npm install
script:
  - gulp build
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh deploy.sh || true'

after_success:
  .cicd/beta_npm_ver.js

deploy:
  skip_cleanup: true
  provider: npm
  email: "konzeptmeister@gmail.com"
  api_key:
    secure: "c9zX0E1LJMAjy3BYTQYT6dI3WRJ/QWD7mUMwtY4PysGCOEbAL+k4P7XAaS4N6l5rBgmN9QsZMDvh18NHKlEnwtNIfBBUq9yc4EvIMynGLbkEwJ/c9JPlRn4U1ND8dBdBbXefYWjUHqXKkRvQfDgDafhmHbJmVPPVnYqlz/HOmb0="
  on:
    branch: develop
    node: 4.1
    condition: "-e /tmp/deployment.flag"
