language: node_js
dist: trusty
sudo: true
node_js:
  - '4.1'
addons:
  firefox: "42.0"
  apt:
    packages:
    - s3cmd
    - ruby
env:
  CXX=g++-4.8

before_install:
  - npm install -g npm@latest
  - gem install sass
  - gem install scss_lint
  - npm install -g gulp

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gulp &

script: 
  - .cicd/w4gulp.js
  - npm run e2e:local
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh deploy.sh || true'

after_success:
  .cicd/beta_npm_ver.js

deploy:
  skip_cleanup: true
  provider: npm
  email: "konzeptmeister@gmail.com"
  api_key:
    secure: "XVJ/QwnTYMNEUMtAcvmVdh6EHndHcEqzdJUe7JYYRXmA2qxhRGIC8VlnK9GKZOS3ACSDygp1lCam+BA5ZYy4QhvsMsPQukWeon6K8Zcerg8Lg3XfxXBilKATf83DQ0PZslus1XgynZmNgUCkJ61rhAhLVOx0iIpetMOHTZ3oJak="
  on:
    branch: develop
    node: 4.1
    condition: "-e /tmp/deployment.flag"
